const sql = {};

sql.planificacions = {};
sql.planificacions.new = "INSERT INTO fresh_tour.planificacions (id_usuario, titulo, comentario, esta_compartida, valoracion, distancia, tempo_visita, tempo_ruta) VALUES ($1, $2, $3, $4, 0, $5, $6, $7) RETURNING id";
sql.planificacions.newLugares = "INSERT INTO fresh_tour.planificacions_lugares_turisticos (id_planificacion, id_lugar_turistico, posicion_visita) VALUES ";
sql.planificacions.newMonumentos = "INSERT INTO fresh_tour.planificacions_monumentos (id_planificacion, id_monumento, posicion_visita) VALUES ";
sql.planificacions.all = "SELECT *, (SELECT usuario FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS usuario, (SELECT id FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS id_actual_usuario, 'Planificación' AS tipo, CASE WHEN EXISTS (SELECT 1 FROM fresh_tour.planificacions_favoritas pf WHERE pf.id_planificacion = p.id AND pf.id_usuario = $1) THEN CAST(1 AS BOOL) ELSE CAST(0 AS BOOL) END AS favorito FROM fresh_tour.planificacions p WHERE esta_compartida = true ORDER BY valoracion DESC"
sql.planificacions.share = "UPDATE fresh_tour.planificacions SET esta_compartida = $1 WHERE id = $2";
sql.planificacions.elementos = "SELECT *, 'Lugar turístico' AS tipo FROM fresh_tour.lugares_turisticos lt WHERE lt.id IN (SELECT id_lugar_turistico FROM fresh_tour.planificacions_lugares_turisticos plt WHERE plt.id_planificacion = $1) UNION all SELECT *, 'Monumento' AS tipo FROM fresh_tour.monumentos m WHERE m.id IN (SELECT id_monumento FROM fresh_tour.planificacions_monumentos pm WHERE pm.id_planificacion = $1)"
sql.planificacions.delete = {}
sql.planificacions.delete.lugares = "DELETE FROM fresh_tour.planificacions_lugares_turisticos WHERE id_planificacion = $1";
sql.planificacions.delete.monumentos = "DELETE FROM fresh_tour.planificacions_monumentos WHERE id_planificacion = $1";
sql.planificacions.delete.planificacion = "DELETE FROM fresh_tour.planificacions WHERE id = $1";
sql.planificacions.delete.comentarios = "DELETE FROM fresh_tour.comentarios_valoracions_planificacions WHERE id_planificacion = $1";
sql.planificacions.delete.favoritas = "DELETE FROM fresh_tour.planificacions_favoritas WHERE id_planificacion = $1";
sql.planificacions.edit = "UPDATE fresh_tour.planificacions SET titulo = $1, comentario = $2 WHERE id = $3";
sql.planificacions.sortBy = {};
sql.planificacions.sortBy.valoracion = "SELECT *, (SELECT usuario FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS usuario, (SELECT id FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS id_actual_usuario, 'Planificación' AS tipo, CASE WHEN EXISTS (SELECT 1 FROM fresh_tour.planificacions_favoritas pf WHERE pf.id_planificacion = p.id AND pf.id_usuario = $1) THEN CAST(1 AS BOOL) ELSE CAST(0 AS BOOL) END AS favorito FROM fresh_tour.planificacions p WHERE esta_compartida = true ORDER BY valoracion DESC";
sql.planificacions.sortBy.menorDistancia = "SELECT *, (SELECT usuario FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS usuario, (SELECT id FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS id_actual_usuario, 'Planificación' AS tipo, CASE WHEN EXISTS (SELECT 1 FROM fresh_tour.planificacions_favoritas pf WHERE pf.id_planificacion = p.id AND pf.id_usuario = $1) THEN CAST(1 AS BOOL) ELSE CAST(0 AS BOOL) END AS favorito FROM fresh_tour.planificacions p WHERE esta_compartida = true ORDER BY distancia DESC";
sql.planificacions.sortBy.maiorDistancia = "SELECT *, (SELECT usuario FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS usuario, (SELECT id FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS id_actual_usuario, 'Planificación' AS tipo, CASE WHEN EXISTS (SELECT 1 FROM fresh_tour.planificacions_favoritas pf WHERE pf.id_planificacion = p.id AND pf.id_usuario = $1) THEN CAST(1 AS BOOL) ELSE CAST(0 AS BOOL) END AS favorito FROM fresh_tour.planificacions p WHERE esta_compartida = true ORDER BY distancia ASC";
sql.planificacions.sortBy.maiorTempoVisita = "SELECT *, (SELECT usuario FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS usuario, (SELECT id FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS id_actual_usuario, 'Planificación' AS tipo, CASE WHEN EXISTS (SELECT 1 FROM fresh_tour.planificacions_favoritas pf WHERE pf.id_planificacion = p.id AND pf.id_usuario = $1) THEN CAST(1 AS BOOL) ELSE CAST(0 AS BOOL) END AS favorito FROM fresh_tour.planificacions p WHERE esta_compartida = true ORDER BY tempo_visita ASC";
sql.planificacions.sortBy.menorTempoVisita = "SELECT *, (SELECT usuario FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS usuario, (SELECT id FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS id_actual_usuario, 'Planificación' AS tipo, CASE WHEN EXISTS (SELECT 1 FROM fresh_tour.planificacions_favoritas pf WHERE pf.id_planificacion = p.id AND pf.id_usuario = $1) THEN CAST(1 AS BOOL) ELSE CAST(0 AS BOOL) END AS favorito FROM fresh_tour.planificacions p WHERE esta_compartida = true ORDER BY tempo_visita DESC";
sql.planificacions.sortBy.maiorTempoRuta = "SELECT *, (SELECT usuario FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS usuario, (SELECT id FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS id_actual_usuario, 'Planificación' AS tipo, CASE WHEN EXISTS (SELECT 1 FROM fresh_tour.planificacions_favoritas pf WHERE pf.id_planificacion = p.id AND pf.id_usuario = $1) THEN CAST(1 AS BOOL) ELSE CAST(0 AS BOOL) END AS favorito FROM fresh_tour.planificacions p WHERE esta_compartida = true ORDER BY tempo_ruta ASC";
sql.planificacions.sortBy.menorTempoRuta = "SELECT *, (SELECT usuario FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS usuario, (SELECT id FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS id_actual_usuario, 'Planificación' AS tipo, CASE WHEN EXISTS (SELECT 1 FROM fresh_tour.planificacions_favoritas pf WHERE pf.id_planificacion = p.id AND pf.id_usuario = $1) THEN CAST(1 AS BOOL) ELSE CAST(0 AS BOOL) END AS favorito FROM fresh_tour.planificacions p WHERE esta_compartida = true ORDER BY tempo_ruta DESC";
sql.planificacions.sortBy.menorTempoTotalRuta = "SELECT *, (SELECT usuario FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS usuario, (SELECT id FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS id_actual_usuario, 'Planificación' AS tipo, CASE WHEN EXISTS (SELECT 1 FROM fresh_tour.planificacions_favoritas pf WHERE pf.id_planificacion = p.id AND pf.id_usuario = $1) THEN CAST(1 AS BOOL) ELSE CAST(0 AS BOOL) END AS favorito FROM fresh_tour.planificacions p WHERE esta_compartida = true ORDER BY (tempo_ruta+tempo_visita) DESC";
sql.planificacions.sortBy.maiorTempoTotalRuta = "SELECT *, (SELECT usuario FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS usuario, (SELECT id FROM fresh_tour.usuarios u WHERE id = p.id_usuario) AS id_actual_usuario, 'Planificación' AS tipo, CASE WHEN EXISTS (SELECT 1 FROM fresh_tour.planificacions_favoritas pf WHERE pf.id_planificacion = p.id AND pf.id_usuario = $1) THEN CAST(1 AS BOOL) ELSE CAST(0 AS BOOL) END AS favorito FROM fresh_tour.planificacions p WHERE esta_compartida = true ORDER BY (tempo_ruta+tempo_visita) ASC";
sql.planificacions.fav.sortBy = {};
sql.planificacions.fav.sortBy.valoracion = "SELECT *,'Planificación' as tipo, true AS favorito, (SELECT id FROM fresh_tour.usuarios u WHERE id = p2.id_usuario) AS id_actual_usuario FROM fresh_tour.planificacions p2 WHERE id IN ( SELECT id_planificacion FROM fresh_tour.planificacions_favoritas pf WHERE id_usuario = $1) ORDER BY valoracion ASC";
sql.planificacions.fav.sortBy.menorDistancia = "SELECT *,'Planificación' as tipo, true AS favorito, (SELECT id FROM fresh_tour.usuarios u WHERE id = p2.id_usuario) AS id_actual_usuario FROM fresh_tour.planificacions p2 WHERE id IN ( SELECT id_planificacion FROM fresh_tour.planificacions_favoritas pf WHERE id_usuario = $1) ORDER BY distancia DESC";
sql.planificacions.fav.sortBy.maiorDistancia = "SELECT *,'Planificación' as tipo, true AS favorito, (SELECT id FROM fresh_tour.usuarios u WHERE id = p2.id_usuario) AS id_actual_usuario FROM fresh_tour.planificacions p2 WHERE id IN ( SELECT id_planificacion FROM fresh_tour.planificacions_favoritas pf WHERE id_usuario = $1) ORDER BY distancia ASC";
sql.planificacions.fav.fav.sortBy.maiorTempoVisita = "SELECT *,'Planificación' as tipo, true AS favorito, (SELECT id FROM fresh_tour.usuarios u WHERE id = p2.id_usuario) AS id_actual_usuario FROM fresh_tour.planificacions p2 WHERE id IN ( SELECT id_planificacion FROM fresh_tour.planificacions_favoritas pf WHERE id_usuario = $1) ORDER BY tempo_visita ASC";
sql.planificacions.fav.sortBy.menorTempoVisita = "SELECT *,'Planificación' as tipo, true AS favorito, (SELECT id FROM fresh_tour.usuarios u WHERE id = p2.id_usuario) AS id_actual_usuario FROM fresh_tour.planificacions p2 WHERE id IN ( SELECT id_planificacion FROM fresh_tour.planificacions_favoritas pf WHERE id_usuario = $1) ORDER BY tempo_visita DESC";
sql.planificacions.fav.sortBy.maiorTempoRuta = "SELECT *,'Planificación' as tipo, true AS favorito, (SELECT id FROM fresh_tour.usuarios u WHERE id = p2.id_usuario) AS id_actual_usuario FROM fresh_tour.planificacions p2 WHERE id IN ( SELECT id_planificacion FROM fresh_tour.planificacions_favoritas pf WHERE id_usuario = $1) ORDER BY tempo_ruta ASC";
sql.planificacions.fav.sortBy.menorTempoRuta = "SELECT *,'Planificación' as tipo, true AS favorito, (SELECT id FROM fresh_tour.usuarios u WHERE id = p2.id_usuario) AS id_actual_usuario FROM fresh_tour.planificacions p2 WHERE id IN ( SELECT id_planificacion FROM fresh_tour.planificacions_favoritas pf WHERE id_usuario = $1) ORDER BY tempo_ruta DESC";
sql.planificacions.fav.sortBy.menorTempoTotalRuta = "SELECT *,'Planificación' as tipo, true AS favorito, (SELECT id FROM fresh_tour.usuarios u WHERE id = p2.id_usuario) AS id_actual_usuario FROM fresh_tour.planificacions p2 WHERE id IN ( SELECT id_planificacion FROM fresh_tour.planificacions_favoritas pf WHERE id_usuario = $1) ORDER BY (tempo_ruta+tempo_visita) DESC";
sql.planificacions.fav.sortBy.maiorTempoTotalRuta = "SELECT *,'Planificación' as tipo, true AS favorito, (SELECT id FROM fresh_tour.usuarios u WHERE id = p2.id_usuario) AS id_actual_usuario FROM fresh_tour.planificacions p2 WHERE id IN ( SELECT id_planificacion FROM fresh_tour.planificacions_favoritas pf WHERE id_usuario = $1) ORDER BY (tempo_ruta+tempo_visita) ASC";

sql.usuarios = {};
sql.usuarios.edit = "UPDATE fresh_tour.usuarios SET usuario=$1, nome=$2, apelidos=$3, email=$4, contrasinal=$5 WHERE id=$6 RETURNING usuario, nome, apelidos, email, to_char(data, 'DD-MM-YY') as data";
sql.usuarios.exists= "SELECT usuario, email FROM fresh_tour.usuarios WHERE usuario LIKE $1 OR email LIKE $2";
sql.usuarios.delete = {};
sql.usuarios.delete.lugaresFav = "DELETE FROM fresh_tour.lugares_turisticos_favoritos WHERE id_usuario = $1";
sql.usuarios.delete.monumentosFav = "DELETE FROM fresh_tour.monumentos_favoritos WHERE id_usuario = $1";
sql.usuarios.delete.planificacionsFav = "DELETE FROM fresh_tour.planificacions_favoritas WHERE id_usuario = $1";
sql.usuarios.delete.comentariosLugares = "DELETE FROM fresh_tour.comentarios_valoracions_lugares_turisticos WHERE id_usuario = $1 RETURNING id_lugar_turistico";
sql.usuarios.delete.comentariosMonumentos = "DELETE FROM fresh_tour.comentarios_valoracions_monumentos WHERE id_usuario = $1 RETURNING id_monumento";
sql.usuarios.delete.comentariosPlanificacions = "DELETE FROM fresh_tour.comentarios_valoracions_planificacions WHERE id_usuario = $1";
sql.usuarios.delete.planificacionsId = "SELECT id FROM fresh_tour.planificacions WHERE id_usuario = $1";
sql.usuarios.delete.user = "DELETE FROM fresh_tour.usuarios WHERE id = $1";

sql.elementos = {};
sql.elementos.sortBy = {};
sql.elementos.sortBy.titulo = "SELECT *, 'Lugar turístico' as tipo, CASE WHEN EXISTS (SELECT 1 FROM fresh_tour.lugares_turisticos_favoritos ltf WHERE ltf.id_lugar_turistico = lt.id AND ltf.id_usuario = $1) THEN CAST(1 AS BOOL) ELSE CAST(0 AS BOOL) END AS favorito FROM fresh_tour.lugares_turisticos lt WHERE prezo is not NULL UNION ALL SELECT *, 'Monumento' as tipo, CASE WHEN EXISTS (SELECT 1 FROM fresh_tour.monumentos_favoritos mf WHERE mf.id_monumento = m.id AND mf.id_usuario = $1) THEN CAST(1 AS BOOL) ELSE CAST(0 AS BOOL) END AS favorito FROM fresh_tour.monumentos m WHERE m.prezo is not NULL ORDER BY titulo ASC"
sql.elementos.sortBy.valoracion = "SELECT *, 'Lugar turístico' as tipo, CASE WHEN EXISTS (SELECT 1 FROM fresh_tour.lugares_turisticos_favoritos ltf WHERE ltf.id_lugar_turistico = lt.id AND ltf.id_usuario = $1) THEN CAST(1 AS BOOL) ELSE CAST(0 AS BOOL) END AS favorito FROM fresh_tour.lugares_turisticos lt WHERE prezo is not NULL UNION ALL SELECT *, 'Monumento' as tipo, CASE WHEN EXISTS (SELECT 1 FROM fresh_tour.monumentos_favoritos mf WHERE mf.id_monumento = m.id AND mf.id_usuario = $1) THEN CAST(1 AS BOOL) ELSE CAST(0 AS BOOL) END AS favorito FROM fresh_tour.monumentos m WHERE m.prezo is not NULL ORDER BY valoracion DESC"
sql.elementos.updateValoracion = {};
sql.elementos.updateValoracion.mediaLugares = "SELECT avg(valoracion) as media FROM fresh_tour.comentarios_valoracions_lugares_turisticos WHERE id_lugar_turistico = $1";
sql.elementos.updateValoracion.updateLugares = "UPDATE fresh_tour.lugares_turisticos SET valoracion = $1 WHERE id = $2"
sql.elementos.updateValoracion.mediaMonumentos = "SELECT avg(valoracion) as media FROM fresh_tour.comentarios_valoracions_monumentos WHERE id_monumento = $1";
sql.elementos.updateValoracion.updateMonumentos = "UPDATE fresh_tour.monumentos SET valoracion = $1 WHERE id = $2"
sql.elementos.byName = "SELECT *, 'Lugar turístico' as tipo, CASE WHEN EXISTS (SELECT 1 FROM fresh_tour.lugares_turisticos_favoritos ltf WHERE ltf.id_lugar_turistico = lt.id AND ltf.id_usuario = $1) THEN CAST(1 AS BOOL) ELSE CAST(0 AS BOOL) END AS favorito FROM fresh_tour.lugares_turisticos lt WHERE lt.prezo is not NULL AND lt.titulo LIKE $2 UNION ALL SELECT *, 'Monumento' as tipo, CASE WHEN EXISTS (SELECT 1 FROM fresh_tour.monumentos_favoritos mf WHERE mf.id_monumento = m.id AND mf.id_usuario = $1) THEN CAST(1 AS BOOL) ELSE CAST(0 AS BOOL) END AS favorito FROM fresh_tour.monumentos m WHERE m.prezo is not NULL AND m.titulo LIKE $2 ORDER BY titulo ASC"
sql.elementos.favs = {};
sql.elementos.favs.sortBy = {};
sql.elementos.favs.sortBy.titulo = "SELECT *, 'Monumento' as tipo, true AS favorito FROM fresh_tour.monumentos m WHERE id IN ( SELECT id_monumento FROM fresh_tour.monumentos_favoritos mf WHERE id_usuario = $1) UNION ALL SELECT *, 'Lugar turístico' as tipo, true AS favorito FROM fresh_tour.lugares_turisticos lt WHERE id IN ( SELECT id_lugar_turistico FROM fresh_tour.lugares_turisticos_favoritos ltf WHERE id_usuario = $1) ORDER BY titulo ASC";
sql.elementos.favs.sortBy.valoracion = "SELECT *, 'Monumento' as tipo, true AS favorito FROM fresh_tour.monumentos m WHERE id IN ( SELECT id_monumento FROM fresh_tour.monumentos_favoritos mf WHERE id_usuario = $1) UNION ALL SELECT *, 'Lugar turístico' as tipo, true AS favorito FROM fresh_tour.lugares_turisticos lt WHERE id IN ( SELECT id_lugar_turistico FROM fresh_tour.lugares_turisticos_favoritos ltf WHERE id_usuario = $1) ORDER BY titulo DESC";

module.exports = sql;