--- CREATE THE DATABASE
---     psql -c "CREATE DATABASE \"osm\" OWNER postgres;"
---     psql -d fresh_tour < create_osm_database.sql
--- IT IS EASIER TO USE A PROGRAM AS DBEAVER IF IT IS POSIBLE
--- YOU CAN CREATE THE DATABASE AND THEN EXECUTE THE SCRIPT
--- OR IF YOU PREFERE, YOU CAN USE THE BELOW SCRIPT LINE

--- CREATE DATABASE osm OWNER postgres;

--- ENABLE postgis
CREATE EXTENSION postgis;
--- ENABLE hstore
CREATE EXTENSION hstore;
--- SCHEMAS CREATION
CREATE SCHEMA IF NOT EXISTS lugares_hospedaxe AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS lugares_hostaleria AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS actividades_ocio AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS outras_actividades AUTHORIZATION postgres;